version: "3.8"
services:
  db:
    image: postgres:16
    container_name: powerplay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: powerplay_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3133"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
