# Generated by Django 5.2.5 on 2025-08-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stát')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO kód')),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy narození',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Název ligy')),
                ('season', models.CharField(max_length=20, verbose_name='Sezóna')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='liga_loga/', verbose_name='Logo')),
                ('date_start', models.DateField(verbose_name='Začátek sezóny')),
                ('date_end', models.DateField(verbose_name='Konec sezóny')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligy',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název stadionu')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('map_url', models.URLField(blank=True, null=True, verbose_name='Mapa')),
            ],
            options={
                'verbose_name': 'Stadion',
                'verbose_name_plural': 'Stadiony',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Datum a čas zápasu')),
                ('time_only', models.TimeField(blank=True, null=True, verbose_name='Čas (volitelné)')),
                ('score_home', models.PositiveIntegerField(default=0, verbose_name='Skóre domácí')),
                ('score_away', models.PositiveIntegerField(default=0, verbose_name='Skóre hosté')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.stadium', verbose_name='Stadion')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Název týmu')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Město')),
                ('coach', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trenér')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_loga/', verbose_name='Logo týmu')),
                ('staff', models.TextField(blank=True, null=True, verbose_name='Realizační tým')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='powerplay_app.league', verbose_name='Liga')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.stadium', verbose_name='Stadion')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Týmy',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=255, verbose_name='Příjmení')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Přezdívka')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E‑mail')),
                ('jersey_number', models.PositiveIntegerField(verbose_name='Číslo dresu')),
                ('position', models.CharField(choices=[('forward', 'Útočník'), ('defense', 'Obránce'), ('goalie', 'Brankář')], max_length=50, verbose_name='Pozice')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.country', verbose_name='Stát')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, '1. třetina'), (2, '2. třetina'), (3, '3. třetina'), (4, 'Prodloužení'), (5, 'Nájezdy')], verbose_name='Třetina')),
                ('second_in_period', models.PositiveIntegerField(verbose_name='Čas v sekundách (od začátku třetiny)')),
                ('minutes', models.PositiveSmallIntegerField(verbose_name='Délka trestu (min)')),
                ('penalty_type', models.CharField(choices=[('2', 'Malý trest (2)'), ('5', 'Velký trest (5)'), ('10', 'Osobní trest (10)'), ('20', 'Do konce utkání (20)')], default='2', max_length=3, verbose_name='Typ trestu')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Důvod')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.game', verbose_name='Zápas')),
                ('penalized_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.player', verbose_name='Faulující hráč')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Trest',
                'verbose_name_plural': 'Tresty',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='1, 2, 3 …; 0 = gólman', verbose_name='Číslo lajny')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='powerplay_app.game', verbose_name='Zápas')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Lajna',
                'verbose_name_plural': 'Lajny',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, '1. třetina'), (2, '2. třetina'), (3, '3. třetina'), (4, 'Prodloužení'), (5, 'Nájezdy')], verbose_name='Třetina')),
                ('second_in_period', models.PositiveIntegerField(verbose_name='Čas v sekundách (od začátku třetiny)')),
                ('strength', models.CharField(choices=[('EV', 'Plný počet'), ('PP', 'Přesilovka'), ('OS', 'Oslabení'), ('EN', 'Do prázdné'), ('PS', 'Trestné střílení')], default='EV', max_length=2, verbose_name='Síla hry')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.game', verbose_name='Zápas')),
                ('assist_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_primary', to='powerplay_app.player', verbose_name='Asistence 1')),
                ('assist_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_secondary', to='powerplay_app.player', verbose_name='Asistence 2')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='powerplay_app.player', verbose_name='Střelec')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Gól',
                'verbose_name_plural': 'Góly',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_away', to='powerplay_app.team', verbose_name='Hostující tým'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_home', to='powerplay_app.team', verbose_name='Domácí tým'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název turnaje')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Začátek')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Konec')),
                ('games', models.ManyToManyField(blank=True, related_name='tournaments', to='powerplay_app.game', verbose_name='Zápasy')),
            ],
            options={
                'verbose_name': 'Turnaj',
                'verbose_name_plural': 'Turnaje',
            },
        ),
        migrations.CreateModel(
            name='LineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('LW', 'Levé křídlo'), ('C', 'Střed'), ('RW', 'Pravé křídlo'), ('LD', 'Levá obrana'), ('RD', 'Pravá obrana'), ('G', 'Brankář')], max_length=2, verbose_name='Post')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='powerplay_app.line', verbose_name='Lajna')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Hráč v lajně',
                'verbose_name_plural': 'Hráči v lajně',
                'unique_together': {('line', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Body')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Góly')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Asistence')),
                ('shots', models.PositiveIntegerField(default=0, verbose_name='Střely')),
                ('penalty_minutes', models.PositiveIntegerField(default=0, verbose_name='Trestné minuty')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='Obdržené góly (gólmani)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='powerplay_app.game', verbose_name='Zápas')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='powerplay_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Statistika hráče',
                'verbose_name_plural': 'Statistiky hráčů',
                'constraints': [models.UniqueConstraint(fields=('player', 'game'), name='uniq_stats_player_game')],
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('team', 'jersey_number'), name='uniq_jersey_per_team'),
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together={('game', 'team', 'line_number')},
        ),
    ]
