# Generated by Django 5.2.5 on 2025-08-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E‑mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Fotografie')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Člen realizačního týmu',
                'verbose_name_plural': 'Realizační tým',
                'ordering': ('team', 'order', 'last_name'),
            },
        ),
    ]
