# Generated by Django 5.2.5 on 2025-08-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='team',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.team'),
        ),
    ]
