# Generated by Django 5.2.5 on 2025-08-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0002_alter_matchlineup_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='assists',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='goals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='goals_conceded',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='penalty_minutes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
