# Generated by Django 5.2.5 on 2025-08-14 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Člen týmu', max_length=255, verbose_name='Funkce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='staff_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámky k realizačnímu týmu'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Zadej platné telefonní číslo (např. +420 123 456 789).', regex='^\\+?[0-9\\- ]{7,20}$')], verbose_name='Telefon'),
        ),
    ]
