# Generated by Django 5.2.5 on 2025-08-11 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0003_alter_matchlineup_assists_alter_matchlineup_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.player'),
        ),
    ]
