# Generated by Django 5.2.5 on 2025-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0003_remove_team_staff_staff_role_team_staff_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Nahraj profilovou fotku hráče (doporučeno 300x300 px).', null=True, upload_to='player_photos/', verbose_name='Profilová fotka'),
        ),
    ]
