# Generated by Django 5.2.5 on 2025-08-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0004_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Doporučeno 300×300 px.', null=True, upload_to='player_photos/', verbose_name='Profilová fotka'),
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('game', 'Zápas'), ('training', 'Trénink'), ('camp', 'Kemp'), ('meeting', 'Porada'), ('other', 'Jiné')], max_length=20, verbose_name='Typ události')),
                ('title', models.CharField(help_text='Krátký popis (např. Trénink A‑tým / Zápas …).', max_length=200, verbose_name='Název')),
                ('starts_at', models.DateTimeField(verbose_name='Začátek')),
                ('ends_at', models.DateTimeField(help_text='Musí být po začátku.', verbose_name='Konec')),
                ('location_text', models.CharField(blank=True, max_length=200, verbose_name='Místo (textem)')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Zrušeno')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('source', models.CharField(choices=[('manual', 'Ručně'), ('game', 'Ze zápasu')], default='manual', max_length=20, verbose_name='Zdroj')),
                ('auto_synced', models.BooleanField(default=False, verbose_name='Automaticky synchronizováno')),
                ('related_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.game', verbose_name='Související zápas')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.stadium', verbose_name='Stadion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Událost týmu',
                'verbose_name_plural': 'Události týmů',
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['team', 'starts_at'], name='powerplay_a_team_id_6e631a_idx'), models.Index(fields=['starts_at'], name='powerplay_a_starts__6e0ca0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('related_game__isnull', False)), fields=('team', 'related_game'), name='uniq_team_event_per_game')],
            },
        ),
    ]
