# Generated by Django 5.2.5 on 2025-08-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0004_staffrole_alter_staffmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('map_url', models.URLField(blank=True, help_text='Odkaz na mapu nebo Google Maps', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='location',
        ),
        migrations.AddField(
            model_name='match',
            name='stadion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.stadion'),
        ),
    ]
