# Generated by Django 5.2.5 on 2025-08-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0004_alter_matchlineup_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='line_number',
            field=models.IntegerField(blank=True, choices=[(1, '1. lajna'), (2, '2. lajna'), (3, '3. lajna'), (4, 'Náhradníci')], null=True),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='position_detail',
            field=models.CharField(blank=True, choices=[('LW', 'Levé křídlo'), ('C', 'Střed'), ('RW', 'Pravé křídlo'), ('LD', 'Levý obránce'), ('RD', 'Pravý obránce'), ('G', 'Brankář')], max_length=2, null=True),
        ),
    ]
