# Generated by Django 5.2.5 on 2025-08-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0005_stadion_remove_match_location_match_stadion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('can_score', models.BooleanField(default=True)),
                ('can_concede', models.BooleanField(default=False)),
                ('can_assist', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='powerplay_app.playerposition'),
        ),
    ]
