# Generated by Django 5.2.5 on 2025-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0005_matchlineup_line_number_matchlineup_position_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
