# Generated by Django 5.2.5 on 2025-08-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0005_alter_player_photo_teamevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.CharField(choices=[('league', 'Ligový zápas'), ('tournament', 'Turnaj'), ('friendly', 'Přátelský')], default='league', help_text='Určuje, zda jde o ligový zápas, turnaj nebo přátelské utkání.', max_length=20, verbose_name='Typ utkání'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Vyplň pouze pokud je Typ utkání = Turnaj.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.tournament', verbose_name='Turnaj'),
        ),
    ]
