# Generated by Django 5.2.5 on 2025-08-15 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0006_game_competition_game_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, help_text='Vyplň pouze u ligového zápasu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.CharField(choices=[('league', 'Ligový zápas'), ('tournament', 'Turnaj'), ('friendly', 'Přátelský')], default='league', help_text='Ligový / Turnaj / Přátelský', max_length=20, verbose_name='Typ utkání'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Vyplň pouze u turnajového zápasu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerplay_app.tournament', verbose_name='Turnaj'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Název ligy'),
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sezóna'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('competition', 'league')), fields=('competition', 'league', 'starts_at', 'home_team', 'away_team'), name='uniq_game_league'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('competition', 'tournament')), fields=('competition', 'tournament', 'starts_at', 'home_team', 'away_team'), name='uniq_game_tournament'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('competition', 'friendly')), fields=('competition', 'starts_at', 'home_team', 'away_team'), name='uniq_game_friendly'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('name', 'season'), name='uniq_league_name_season'),
        ),
    ]
