# Generated by Django 5.2.5 on 2025-08-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0007_game_league_alter_game_competition_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamevent',
            name='uniq_team_event_per_game',
        ),
        migrations.AlterField(
            model_name='teamevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='powerplay_app.team', verbose_name='Tým'),
        ),
        migrations.AlterField(
            model_name='teamevent',
            name='title',
            field=models.CharField(help_text='Krátký popis (např. Trénink / Zápas …).', max_length=200, verbose_name='Název'),
        ),
        migrations.AddConstraint(
            model_name='teamevent',
            constraint=models.UniqueConstraint(condition=models.Q(('related_game__isnull', False)), fields=('related_game',), name='uniq_event_per_game'),
        ),
    ]
