# Generated by Django 5.2.5 on 2025-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0007_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerposition',
            name='position_type',
            field=models.CharField(choices=[('Offensive', 'Offensive'), ('Defensive', 'Defensive'), ('Goalkeeper', 'Goalkeeper')], default='Offensive', max_length=20),
        ),
    ]
