# Generated by Django 5.2.5 on 2025-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0007_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='photos_staff',
            field=models.ImageField(blank=True, null=True, upload_to='match_reports/photos/'),
        ),
    ]
