# Generated by Django 5.2.5 on 2025-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0008_remove_teamevent_uniq_team_event_per_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamevent',
            name='title',
            field=models.CharField(help_text='Krátký popis (např. Trénink A-tým / Zápas …).', max_length=200, verbose_name='Název'),
        ),
    ]
