# Generated by Django 5.2.5 on 2025-08-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0008_staffrole_email_staffrole_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrole',
            name='photos_staff',
        ),
        migrations.AddField(
            model_name='staffrole',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
    ]
