# Generated by Django 5.2.5 on 2025-08-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0009_alter_teamevent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='powerplay_app.game', verbose_name='Zápas')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='powerplay_app.player', verbose_name='Hráč')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Nominace do zápasu',
                'verbose_name_plural': 'Nominace do zápasu',
                'constraints': [models.UniqueConstraint(fields=('game', 'player'), name='uniq_nomination_game_player')],
            },
        ),
    ]
