# Generated by Django 5.2.5 on 2025-08-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0010_gamenomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineassignment',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.player', verbose_name='Hráč'),
        ),
    ]
