# Generated by Django 5.2.5 on 2025-08-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0011_alter_lineassignment_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonTotals',
            fields=[
            ],
            options={
                'verbose_name': 'Souhrnná statistika hráče',
                'verbose_name_plural': 'Souhrnné statistiky hráčů',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('powerplay_app.player',),
        ),
        migrations.AlterField(
            model_name='goal',
            name='second_in_period',
            field=models.PositiveIntegerField(verbose_name='Čas'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='second_in_period',
            field=models.PositiveIntegerField(verbose_name='Čas'),
        ),
        migrations.CreateModel(
            name='WalletCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Název')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_categories', to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Kategorie pokladny',
                'verbose_name_plural': 'Kategorie pokladny',
                'ordering': ('team', 'order', 'name'),
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'Příjem'), ('out', 'Výdaj')], max_length=4, verbose_name='Typ')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='powerplay_app.walletcategory', verbose_name='Kategorie')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Položka pokladny',
                'verbose_name_plural': 'Položky pokladny',
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['team', 'date'], name='powerplay_a_team_id_fc1b0d_idx')],
            },
        ),
    ]
