# Generated by Django 5.2.5 on 2025-08-25 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0012_playerseasontotals_alter_goal_second_in_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=120, verbose_name='Předmět')),
                ('message', models.TextField(verbose_name='Připomínka')),
                ('status', models.CharField(choices=[('open', 'Otevřeno'), ('closed', 'Uzavřeno')], default='open', max_length=12, verbose_name='Stav')),
                ('created_by_name', models.CharField(blank=True, max_length=120, verbose_name='Autor (jméno zapsané při vytvoření)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Autor (uživatel)')),
                ('related_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='powerplay_app.game', verbose_name='Zápas')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='powerplay_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Připomínka',
                'verbose_name_plural': 'Připomínky',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['team', 'created_at'], name='powerplay_a_team_id_ceae22_idx')],
            },
        ),
    ]
