# Generated by Django 5.2.5 on 2025-08-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0013_gamefeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamefeedback',
            options={'ordering': ('-created_at',), 'verbose_name': 'Připomínka', 'verbose_name_plural': 'Připomínky'},
        ),
        migrations.RemoveField(
            model_name='gamefeedback',
            name='status',
        ),
        migrations.AddField(
            model_name='gamefeedback',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='powerplay_app.teamevent', verbose_name='Událost'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil (uživatel)'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Jméno autora (snapshot)'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='message',
            field=models.TextField(verbose_name='Zpráva'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='related_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='powerplay_app.game', verbose_name='Zápas'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='powerplay_app.team', verbose_name='Tým'),
        ),
    ]
