# Generated by Django 5.2.5 on 2025-08-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0014_alter_gamefeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role_description',
            field=models.TextField(blank=True, verbose_name='Popis funkce'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
