# Generated by Django 5.2.5 on 2025-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0015_staff_role_description_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stadiums/', verbose_name='Foto stadionu'),
        ),
        migrations.AddField(
            model_name='team',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Obecný e-mail'),
        ),
        migrations.AddField(
            model_name='team',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Web klubu'),
        ),
    ]
