# Generated by Django 5.2.5 on 2025-08-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerplay_app', '0017_game_external_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, help_text='Vyplň pouze u ligového zápasu.', null=True, on_delete=django.db.models.deletion.CASCADE, to='powerplay_app.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='powerplay_app.league', verbose_name='Liga'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition', 'league'), _negated=True), ('league__isnull', False), _connector='OR'), name='chk_game_league_required_for_league_comp'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition', 'tournament'), _negated=True), ('tournament__isnull', False), _connector='OR'), name='chk_game_tournament_required_for_tournament_comp'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition', 'friendly'), _negated=True), models.Q(('league__isnull', True), ('tournament__isnull', True)), _connector='OR'), name='chk_game_friendly_requires_no_refs'),
        ),
    ]
